"""empty message

Revision ID: df4133e9f4bf
Revises: e93fc5e7f96d
Create Date: 2022-05-17 12:16:22.370931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df4133e9f4bf'
down_revision = 'e93fc5e7f96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('lang_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('language_id', sa.Integer(), nullable=True))
    op.alter_column('books', 'genre',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'books', 'genre', ['genre'], ['id'])
    op.create_foreign_key(None, 'books', 'language', ['language_id'], ['id'])
    op.drop_column('books', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('language', mysql.VARCHAR(length=2), nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.alter_column('books', 'genre',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
    op.drop_column('books', 'language_id')
    op.drop_table('language')
    op.drop_table('genre')
    # ### end Alembic commands ###
